import { useEffect } from "react";
import { useParams, Link } from "react-router-dom";
import { MarkdownRenderer } from "@/components/shared";

const TERMS_CONTENT = `# Terms of Use

*Last updated: May 5, 2026*

## 1. Acceptance of Terms

By accessing or using DocForge ("Service"), you agree to be bound by these Terms of Use. If you do not agree, do not use the Service.

## 2. Description of Service

DocForge is an AI-powered document generation platform provided as a software-as-a-service (SaaS). The Service is currently in an **MVP / experimental stage** and may be modified, suspended, or discontinued at any time without prior notice.

## 3. Acceptable Use

You agree not to use the Service to:

- Violate any applicable law or regulation
- Generate content that is harmful, fraudulent, defamatory, abusive, or otherwise unlawful
- Attempt to reverse-engineer, circumvent security controls, or overload the platform's infrastructure
- Infringe the intellectual property rights of any third party

## 4. User Accounts

You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. Notify us immediately at **maxjneto@gmail.com** if you suspect unauthorised access.

## 5. AI-Generated Content

Content generated by the Service is produced by artificial intelligence models and **may contain errors, inaccuracies, or omissions**. DocForge does not guarantee the accuracy, completeness, or fitness of AI-generated content for any particular purpose. All output must be reviewed and validated by a qualified human before use in any professional, legal, technical, or other context.

## 6. Disclaimer of Warranties

The Service is provided **"as is"** and **"as available"**, without warranties of any kind, express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, or non-infringement.

## 7. Limitation of Liability

To the maximum extent permitted by applicable law, DocForge and its creator shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or in connection with your use of the Service.

## 8. Account Suspension and Termination

DocForge reserves the right to suspend or terminate your access to the Service at any time, for any reason, including but not limited to violation of these Terms or misuse of the platform.

## 9. Governing Law

These Terms are governed by and construed in accordance with the laws of the **Federative Republic of Brazil**. Any disputes shall be submitted to the competent courts of Brazil.

## 10. Changes to These Terms

We may update these Terms from time to time. Continued use of the Service after changes constitutes acceptance of the updated Terms.

## 11. Contact

For questions about these Terms, contact: **maxjneto@gmail.com**
`;

const PRIVACY_CONTENT = `# Privacy Policy

*Last updated: May 5, 2026*

This Privacy Policy describes how DocForge collects, uses, and shares information when you use the Service, in compliance with the **Lei Geral de Proteção de Dados (LGPD)** - Brazilian Federal Law No. 13,709/2018.

## 1. Data We Collect

| Category | Examples |
|---|---|
| Authentication data | Email address, user ID (via Clerk) |
| User content | Documents, prompts, and inputs you create |
| Usage metadata | Timestamps, phase interactions, session activity |

## 2. How We Collect It

- **At registration and login** - via Clerk authentication (OAuth or email/password)
- **During use** - when you create or interact with documents on the platform

## 3. Purpose of Processing

| Purpose | Legal Basis (LGPD Art. 7) |
|---|---|
| Authentication and account management | Execution of contract (Art. 7, V) |
| Document generation and storage | Execution of contract (Art. 7, V) |
| Service improvement and debugging | Legitimate interest (Art. 7, IX) |

## 4. Data Sharing

| Provider | Purpose |
|---|---|
| **Clerk** | Authentication and identity management |
| **Azure OpenAI (Microsoft)** | AI-powered document generation |

We do not sell your personal data to third parties.

## 5. Data Storage and Retention

Data is stored in a PostgreSQL database hosted on Microsoft Azure. We retain your data for as long as your account is active. Upon account deletion, data will be removed within **30 days**.

## 6. Your Rights (LGPD Art. 18)

You have the right to access, correct, delete, and port your data, as well as to revoke consent and request information about sharing. To exercise these rights, contact: **maxjneto@gmail.com**

## 7. Security

We implement HTTPS transport encryption, credential management via Clerk, and access-controlled infrastructure. No internet transmission is 100% secure.

## 8. Children's Privacy

The Service is not directed at individuals under 18. We do not knowingly collect data from minors.

## 9. Changes to This Policy

Continued use of the Service after updates constitutes acceptance of the revised policy.

## 10. Contact

**maxjneto@gmail.com**
`;

const CONTENT: Record<string, { title: string; body: string }> = {
  terms: { title: "Terms of Use", body: TERMS_CONTENT },
  privacy: { title: "Privacy Policy", body: PRIVACY_CONTENT },
};

export function LegalPage() {
  const { doc } = useParams<{ doc: string }>();
  const page = CONTENT[doc ?? ""] ?? CONTENT.terms;

  useEffect(() => {
    document.body.style.overflow = "auto";
  }, []);

  return (
    <div style={{ background: "#0d0e0f", color: "#e3e2e2", minHeight: "100vh", fontFamily: "Inter, sans-serif", overflowY: "auto" }}>
      {/* Header */}
      <header style={{ borderBottom: "1px solid rgba(255,255,255,0.05)", padding: "16px 32px", display: "flex", alignItems: "center", gap: "16px", maxWidth: "800px", margin: "0 auto" }}>
        <Link
          to="/"
          style={{ fontSize: "11px", fontWeight: 600, letterSpacing: "0.05em", textTransform: "uppercase", color: "rgba(255,77,0,0.8)", textDecoration: "none" }}
        >
          ← Back
        </Link>
        <span style={{ color: "rgba(255,255,255,0.2)" }}>|</span>
        <span style={{ fontSize: "11px", fontWeight: 600, letterSpacing: "0.05em", textTransform: "uppercase", color: "#c8c6c5" }}>
          {page.title}
        </span>
      </header>

      {/* Content */}
      <main style={{ maxWidth: "800px", margin: "0 auto", padding: "48px 32px 80px" }}>
        <MarkdownRenderer content={page.body} variant="chat" />
      </main>

      {/* Footer */}
      <footer style={{ borderTop: "1px solid rgba(255,255,255,0.05)", padding: "24px 32px", maxWidth: "800px", margin: "0 auto" }}>
        <p style={{ fontSize: "11px", color: "rgba(200,198,197,0.4)", margin: 0 }}>
          © 2026 Max José de Aragão Neto · DocForge ·{" "}
          <a href="mailto:maxjneto@gmail.com" style={{ color: "rgba(255,77,0,0.6)", textDecoration: "none" }}>
            maxjneto@gmail.com
          </a>
        </p>
      </footer>
    </div>
  );
}
